import Head from "next/head";
import Header from "./Components/Header";
import TopSwiper from "./Components/TopSwiper";
import Image from "next/image";
import CryptoList from "./Components/CryptoList";

// import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <Header />
      </header>

      <main>
        <TopSwiper />
        <CryptoList />
      </main>
    </div>
  );
}
